
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - namespace
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secret
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - server.naveensrinivasan.dev
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - server.naveensrinivasan.dev
  resources:
  - secrets/status
  verbs:
  - get
  - patch
  - update
